"""Tests for Azure resource extraction and attribute normalisation (AZR-01). Wave 0 stubs."""
import pytest


@pytest.mark.skip("Wave 0 stub — implementation in Plan 02")
class TestAzureParser:
    def test_vnet_extracted(self): ...
    def test_nsg_extracted(self): ...
    def test_provider_set_to_azurerm(self): ...
    def test_location_mapped_to_region(self): ...
    def test_storage_account_extracted(self): ...
    def test_aks_extracted(self): ...
