"""Tests for custom policy engine (POL-01, POL-02). Wave 0 stubs."""
import pytest


@pytest.mark.skip("Wave 0 stub — implementation in Plan 06")
class TestPolicyLoader:
    def test_loads_yaml_from_directory(self): ...
    def test_empty_dir_returns_empty(self): ...


@pytest.mark.skip("Wave 0 stub — implementation in Plan 06")
class TestPolicyEvaluation:
    def test_policy_source_injected(self): ...
    def test_policy_finding_has_correct_rule_id(self): ...
    def test_security_and_policy_findings_coexist(self): ...
