"""Tests for shadow infrastructure detector (SHD-01, SHD-02). Wave 0 stubs."""
import pytest


@pytest.mark.skip("Wave 0 stub — implementation in Plan 04")
class TestShadowDetectorImport:
    def test_missing_boto3_raises_runtime_error(self): ...
    def test_no_credentials_raises_runtime_error(self): ...


@pytest.mark.skip("Wave 0 stub — implementation in Plan 04")
class TestShadowDetection:
    def test_no_shadow_when_all_managed(self): ...
    def test_shadow_ec2_flagged(self): ...
    def test_shadow_s3_flagged(self): ...
