import type { ResourceGraph } from './types';

export const sampleData: ResourceGraph = {
  version: '1.0',
  metadata: {
    scan_id: 'demo-001',
    project: 'demo-infrastructure',
    provider: 'aws',
    scanned_at: new Date().toISOString(),
    terraform_version: '1.7.0',
  },
  nodes: [
    {
      id: 'aws_vpc.main',
      type: 'aws_vpc',
      name: 'main',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: '',
      attributes: { cidr_block: '10.0.0.0/16' },
      dependencies: [],
      findings: [],
      cost: { monthly_usd: 0, currency: 'USD', basis: '' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_subnet.public',
      type: 'aws_subnet',
      name: 'public',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: 'vpc:aws_vpc.main',
      attributes: { cidr_block: '10.0.1.0/24', vpc_id: 'aws_vpc.main' },
      dependencies: ['aws_vpc.main'],
      findings: [],
      cost: { monthly_usd: 0, currency: 'USD', basis: '' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_subnet.private',
      type: 'aws_subnet',
      name: 'private',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: 'vpc:aws_vpc.main',
      attributes: { cidr_block: '10.0.2.0/24', vpc_id: 'aws_vpc.main' },
      dependencies: ['aws_vpc.main'],
      findings: [],
      cost: { monthly_usd: 0, currency: 'USD', basis: '' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_security_group.web',
      type: 'aws_security_group',
      name: 'web',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: 'vpc:aws_vpc.main',
      attributes: { name: 'web-sg', vpc_id: 'aws_vpc.main' },
      dependencies: ['aws_vpc.main'],
      findings: [
        {
          rule_id: 'SEC-003',
          severity: 'critical',
          title: 'Security Group Allows SSH from Internet',
          description: 'Ingress rule allows SSH from 0.0.0.0/0',
          remediation: 'Restrict SSH access to specific IP ranges',
          evidence: { cidr_blocks: ['0.0.0.0/0'], port: 22 },
        },
      ],
      cost: { monthly_usd: 0, currency: 'USD', basis: '' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_alb.web',
      type: 'aws_alb',
      name: 'web',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: 'vpc:aws_vpc.main',
      attributes: { internal: false },
      dependencies: ['aws_subnet.public', 'aws_security_group.web'],
      findings: [],
      cost: { monthly_usd: 22.5, currency: 'USD', basis: 'ALB fixed hourly rate' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_instance.web_1',
      type: 'aws_instance',
      name: 'web_1',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: 'vpc:aws_vpc.main',
      attributes: { instance_type: 't3.medium', ami: 'ami-0c55b159cbfafe1f0' },
      dependencies: ['aws_subnet.public', 'aws_security_group.web'],
      findings: [
        {
          rule_id: 'SEC-008',
          severity: 'high',
          title: 'EBS Volume Unencrypted',
          description: 'Root block device is not encrypted',
          remediation: 'Enable encryption on root_block_device',
          evidence: { attribute: 'root_block_device.encrypted', value: null },
        },
      ],
      cost: { monthly_usd: 30.37, currency: 'USD', basis: 't3.medium @ $0.0416/hr' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_instance.web_2',
      type: 'aws_instance',
      name: 'web_2',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: 'vpc:aws_vpc.main',
      attributes: { instance_type: 't3.medium', ami: 'ami-0c55b159cbfafe1f0' },
      dependencies: ['aws_subnet.private', 'aws_security_group.web'],
      findings: [],
      cost: { monthly_usd: 30.37, currency: 'USD', basis: 't3.medium @ $0.0416/hr' },
      drift: 'changed',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_db_instance.main',
      type: 'aws_db_instance',
      name: 'main',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: '',
      attributes: { engine: 'postgresql', instance_class: 'db.r6g.large', storage_encrypted: true },
      dependencies: ['aws_subnet.private'],
      findings: [],
      cost: { monthly_usd: 175.2, currency: 'USD', basis: 'db.r6g.large @ $0.24/hr' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_s3_bucket.assets',
      type: 'aws_s3_bucket',
      name: 'assets',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: '',
      attributes: { bucket: 'myapp-assets', acl: 'private' },
      dependencies: [],
      findings: [
        {
          rule_id: 'SEC-002',
          severity: 'high',
          title: 'S3 Bucket Missing Encryption',
          description: 'No server-side encryption configured',
          remediation: 'Enable SSE-S3 or SSE-KMS encryption',
          evidence: { attribute: 'server_side_encryption_configuration', value: null },
        },
      ],
      cost: { monthly_usd: 12.0, currency: 'USD', basis: '~500GB Standard' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_kms_key.main',
      type: 'aws_kms_key',
      name: 'main',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: '',
      attributes: { description: 'Main encryption key' },
      dependencies: [],
      findings: [
        {
          rule_id: 'SEC-009',
          severity: 'medium',
          title: 'KMS Key Rotation Disabled',
          description: 'Automatic key rotation is not enabled',
          remediation: 'Set enable_key_rotation = true',
          evidence: { attribute: 'enable_key_rotation', value: null },
        },
      ],
      cost: { monthly_usd: 1.0, currency: 'USD', basis: '$1/mo per key' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_iam_role.lambda_exec',
      type: 'aws_iam_role',
      name: 'lambda_exec',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: '',
      attributes: { name: 'lambda-execution-role' },
      dependencies: [],
      findings: [],
      cost: { monthly_usd: 0, currency: 'USD', basis: '' },
      drift: 'unchanged',
      position: { x: 0, y: 0 },
    },
    {
      id: 'aws_lambda_function.processor',
      type: 'aws_lambda_function',
      name: 'processor',
      provider: 'aws',
      module: '',
      region: 'us-east-1',
      group: '',
      attributes: { runtime: 'python3.12', handler: 'index.handler', memory_size: 512 },
      dependencies: ['aws_iam_role.lambda_exec', 'aws_s3_bucket.assets'],
      findings: [
        {
          rule_id: 'SEC-010',
          severity: 'info',
          title: 'Missing Required Tags',
          description: 'Resource is missing Name and Environment tags',
          remediation: 'Add tags block with Name and Environment tags',
          evidence: { missing_tags: ['Name', 'Environment'] },
        },
      ],
      cost: { monthly_usd: 8.5, currency: 'USD', basis: '~2M invocations/mo' },
      drift: 'added',
      position: { x: 0, y: 0 },
    },
  ],
  edges: [
    { source: 'aws_subnet.public', target: 'aws_vpc.main', type: 'implicit' },
    { source: 'aws_subnet.private', target: 'aws_vpc.main', type: 'implicit' },
    { source: 'aws_security_group.web', target: 'aws_vpc.main', type: 'implicit' },
    { source: 'aws_alb.web', target: 'aws_subnet.public', type: 'implicit' },
    { source: 'aws_alb.web', target: 'aws_security_group.web', type: 'implicit' },
    { source: 'aws_instance.web_1', target: 'aws_subnet.public', type: 'implicit' },
    { source: 'aws_instance.web_1', target: 'aws_security_group.web', type: 'implicit' },
    { source: 'aws_instance.web_2', target: 'aws_subnet.private', type: 'implicit' },
    { source: 'aws_instance.web_2', target: 'aws_security_group.web', type: 'implicit' },
    { source: 'aws_db_instance.main', target: 'aws_subnet.private', type: 'implicit' },
    { source: 'aws_lambda_function.processor', target: 'aws_iam_role.lambda_exec', type: 'implicit' },
    { source: 'aws_lambda_function.processor', target: 'aws_s3_bucket.assets', type: 'implicit' },
  ],
  summary: {
    total_resources: 12,
    findings: { critical: 1, high: 2, medium: 1, info: 1 },
    estimated_monthly_cost: 279.94,
    score: 45,
    drift: { added: 1, changed: 1, deleted: 0 },
  },
};
